### PR TITLE
added requirements.txt

### PR DESCRIPTION
**Pull request by erolrecep**
To check required packages to download images from isic-archive.com

### CODE REVIEW

**Comment by GalAvineri** [comment]
I went through the files and saw that the external libraries that are required are indeed requests and Pillow, but i belive that shutil is in the standard library since python 2.3. Do you think it should still be included in the requirements file?

**Comment by erolrecep** [comment]
Yeah, you are right, shutil is a built-in library. I removed from the txt file.
Thanks.

**Comment by GalAvineri** [comment]
Actually another thing that i noticed is that the library that should be downloaded is Pillow and not image, am i right? :)

**Comment by erolrecep** [comment]
When I run the script, it said that "Module not found PIL". I checked the stackoverflow and I found [this](https://stackoverflow.com/questions/8863917/importerror-no-module-named-pil) solution. Then I installed image and did run again. It's resolved. :) I haven't used pillow before and image.

**Comment by GalAvineri** [comment]
I see :) The way i used to install the PIL library is using ```pip install Pillow```. 
I'll update the Readme to have instructions on how to correctly install all the dependencies as well :)

**Pull request merged**
